# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d00ee1107f57509f343347457ccafa41a39c58da49b181373c29d8d2c9961b0c325e832f4463b460d2bf75677b4173013c4cbd64421557bfd03ec27cc2928da

test:
  secret_key_base: e5252421f112c3766ecd44751de98c930bdf65106e97ae0c78ec11b6a1dcd800d8af69d0f5a0a3216311c5d194861445af4e05593ff82d5231b107fa2c94266f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
